//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public string id { get; set; }
        public Nullable<int> kaktus_id { get; set; }
        public Nullable<int> vistavka_id { get; set; }
    
        public virtual kaktusi kaktusi { get; set; }
        public virtual Vistavki Vistavki { get; set; }
    }
}
